name: Check presence of winget
on:
  workflow_dispatch: # manual trigger
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-latest, windows-11-arm]
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: powershell # instead of default pwsh
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - run: |
        . .\install-common.ps1
        Check-WinGet
        winget install --accept-package-agreements --accept-source-agreements --disable-interactivity tsduck
