name: Test SRT installation
on:
  workflow_dispatch: # manual trigger
jobs:
  installation:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - run: ./install-libsrt.ps1 -GitHubActions -NoPause
