name: Install Python on GitHub runner
on:
  workflow_dispatch: # manual trigger
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runner: [windows-latest, windows-11-arm]
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: powershell # instead of default pwsh
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - name: Before installation
      run: |
        Write-Output "=== Default python:"
        $a = Get-Command -ErrorAction SilentlyContinue python
        if ($a -ne $null) {
            $a.Source
            python --version
        }
        Write-Output "=== All python:"
        foreach ($dir in $env:Path -split ';') {
            if (Test-Path "$dir\python.exe") {
                "$dir\python.exe"
            }
        }
        Write-Output "=== Path:"
        $env:Path -split ';'
    - name: Installation
      run: |
        Write-Output "=== Path before installation:"
        $env:Path -split ';'
        .\install-python.ps1 -GitHubActions -NoPause
        Write-Output "=== Path after installation:"
        $env:Path -split ';'
    - name: After installation
      run: |
        Write-Output "=== Default python:"
        $a = Get-Command -ErrorAction SilentlyContinue python
        if ($a -ne $null) {
            $a.Source
        }
        Write-Output "=== All python:"
        foreach ($dir in $env:Path -split ';') {
            if (Test-Path "$dir\python.exe") {
                "$dir\python.exe"
            }
        }
        Write-Output "=== Path:"
        $env:Path -split ';'
        python --version
