name: Test SRT installation
on:
  workflow_dispatch: # manual trigger
jobs:
  installation:
    runs-on: windows-latest
    env:
      # The repo secret "GUEST_TOKEN" is a GitHub token without any privilege, just avoiding
      # rate limits when using the GitHub API when downloading some prerequisites from GitHub.
      GITHUB_TOKEN: ${{ secrets.GUEST_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - run: ./install-libsrt.ps1 -GitHubActions -NoPause
